// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlLsEwLo0MaBU-NiGRJsVIoqPQj4Yg0g',
    appId: '1:567381549461:web:c70afa97d0e2e41de2d69c',
    messagingSenderId: '567381549461',
    projectId: 'todo-app-1d28d',
    authDomain: 'todo-app-1d28d.firebaseapp.com',
    storageBucket: 'todo-app-1d28d.appspot.com',
    measurementId: 'G-QH70ND1XVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8IeRVwptVlfezG9vxD2uVrji8fRtufSA',
    appId: '1:567381549461:android:81ac63b56a13940fe2d69c',
    messagingSenderId: '567381549461',
    projectId: 'todo-app-1d28d',
    storageBucket: 'todo-app-1d28d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE9h188Hi3WYAmYaoZWb71C2vtxEpMMXU',
    appId: '1:567381549461:ios:44348dd357ba3323e2d69c',
    messagingSenderId: '567381549461',
    projectId: 'todo-app-1d28d',
    storageBucket: 'todo-app-1d28d.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE9h188Hi3WYAmYaoZWb71C2vtxEpMMXU',
    appId: '1:567381549461:ios:44348dd357ba3323e2d69c',
    messagingSenderId: '567381549461',
    projectId: 'todo-app-1d28d',
    storageBucket: 'todo-app-1d28d.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmlLsEwLo0MaBU-NiGRJsVIoqPQj4Yg0g',
    appId: '1:567381549461:web:a7e6837a462a7df6e2d69c',
    messagingSenderId: '567381549461',
    projectId: 'todo-app-1d28d',
    authDomain: 'todo-app-1d28d.firebaseapp.com',
    storageBucket: 'todo-app-1d28d.appspot.com',
    measurementId: 'G-GT1WLQNFR5',
  );
}
